### PR TITLE
Adding unit test for amortizationValue

### PR DESCRIPTION
**Pull request by mozts2005**
Unit test for issue #43

amortization value incorrect for purchases date and maturity date

### CODE REVIEW

**Comment by igitur** [comment]
Can you fix this commit so that only the relevant part of the file has changed? It just makes the commit process so much easier.

**Comment by mozts2005** [comment]
I think I have done it

**Comment by mozts2005** [comment]
Any update for this issue?

**Comment by igitur** [comment]
Sorry, no update yet. When I looked at this PR, I noticed a some inconsistencies between QuantLib's test suite and QLNet's test suite. It's my goal to align the 2 projects as much as possible. I'll look at it soon again.

**Comment by igitur** [comment]
Looking at this again. I can merge this PR which adds tests, but if you're looking to make the new tests pass, you'll have to ask on the QuantLib forum. QLNet is a port of QuantLib, so when they fix it, I can port the fix to QLNet.

**Pull request closed without merging**
