### PR TITLE
Following the convention of Quant lib, default is to allow negative rates

### PR DESCRIPTION
**Pull request by screig**
Luigi Ballabio:
http://quantlib.10058.n7.nabble.com/QL-NEGATIVE-RATES-td15367.html

### CODE REVIEW

**Comment by screig** [comment]
hmm, not sure why the test failed. Allowing negative rates should not cause a failure, not been amusing here but is that test correct.

Without this flag I cannot build a EUR yield curve.

**Comment by amaggiulli** [comment]
Your PR is ok , the fail regard a random failure on AppVeyor build , I rerun AppVeyor build now.

**Comment by screig** [comment]
Sorry new to this, should I add this to the dev branch?

**Comment by amaggiulli** [comment]
Yes , thanks . Read the ReadMe.md is all explained ( section Developments workflow ).

**Pull request closed without merging**
