### PR TITLE
typos

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by igitur** [comment]
Thanks.

**Comment by amaggiulli** [comment]
Please don't merge on master , as README say " Note that features(fix) will never be merged directly into master" , every pull request must go on develop . Master is for release building only.
Thank you

**Comment by amaggiulli** [comment]
I revert this and make develop the develop branch as default , hope this will make more easy follow our rules on pull request .

**Comment by igitur** [comment]
Sorry for merging without reading properly.

**Pull request merged**
