### PR TITLE
Added IPrepayModel interface, ConstantCPR class, and updated MBSFixed…

### PR DESCRIPTION
**Pull request by vina0007**
…RateBond to use the interface rather than the PSACurve class.

The MBSFixedRateBond needs some updates... will be pushing that out with corresponding tests using Bloomberg as the control point in the near term.

### CODE REVIEW

**Comment by igitur** [comment]
Welcome to the team! Thanks for contributing.

**Comment by amaggiulli** [comment]
Merged into branch 1.6 ( https://github.com/amaggiulli/qlnet/commit/df84113411be0a55e13f83a2c531fd5b22a12b77). I have done some minor refactoring to separate classes and interfaces. Thx @vina0007 .

**Comment by vina0007** [comment]
thanks for including the changes.  i'm close to having another update for
MBS.  are there guidelines for the class signatures in terms of backward
compatibility?  the reason i ask is there is nothing in quantlib for MBS to
use as a guideline.

**Comment by amaggiulli** [comment]
Not really , as the classes are new there is no backward compatibility to follow . Just clone the 1.6 branch and pull requests there .

**Pull request closed without merging**
