### PR TITLE
Instantiate generic classes using expression tree, instead of new keyword

### PR DESCRIPTION
**Pull request by igitur**
When `T` is a generic class, `new T()` is slow. In fact, it is just syntactic sugar and the actual code that is emitted to IL is `Activator.CreateInstance<T>();`, which uses reflection. A much faster way is to use lambda expression trees. There are many discussions on the web that describe this, e.g. http://stackoverflow.com/questions/6069661/does-system-activator-createinstancet-have-performance-issues-big-enough-to-di

I admit that it doesn't make a big difference in our test suite, but in a scenario where the user will create many thousands of the same object, it will make a difference. I have a test app that demonstrates the impact.

### CODE REVIEW

**Comment by igitur** [comment]
Sample program to illustrate different instantiate methods.
```c#

   public class TestClass
   {
   }

   public static class New<T> where T : new()
   {
      public static readonly Func<T> Instance = Expression.Lambda<Func<T>>(Expression.New(typeof(T))).Compile();
   }

   class Program
   {

      static void Main(string[] args)
      {
         const int IterationCount = 100000000;

         // warmup
         Test1();
         Test2();
         Test3();
         Test4<TestClass>();
         Test5<TestClass>();
         Test6<TestClass>();
         Test7<TestClass>();

         // profile Activator.CreateInstance<T>()
         Stopwatch sw = Stopwatch.StartNew();
         for (int index = 0; index < IterationCount; index++)
            Test1();
         sw.Stop();
         Console.WriteLine("Test1 - Activator.CreateInstance<T>(): {0}", sw.ElapsedMilliseconds);

         // profile new T()
         sw.Restart();
         for (int index = 0; index < IterationCount; index++)
            Test2();
         sw.Stop();
         Console.WriteLine("Test2 - new T() {0}", sw.ElapsedMilliseconds);

         // profile Delegate
         sw.Restart();
         for (int index = 0; index < IterationCount; index++)
            Test3();
         sw.Stop();
         Console.WriteLine("Test3 - Delegate {0}", sw.ElapsedMilliseconds);

         // profile generic new()
         sw.Restart();
         for (int index = 0; index < IterationCount; index++)
		 	Test4<TestClass>();
         sw.Stop();
         Console.WriteLine("Test4 - Generic new() {0}", sw.ElapsedMilliseconds);

         // generic Activator without bindings
         sw.Restart();
         for (int index = 0; index < IterationCount; index++)
			 Test5<TestClass>();
         sw.Stop();
         Console.WriteLine("Test5 - Generic activator {0}", sw.ElapsedMilliseconds);

         // profile Activator with bindings
         sw.Restart();
         for (int index = 0; index < IterationCount; index++)
            Test6<TestClass>();
         sw.Stop();
         Console.WriteLine("Test6 - Generic activator with bindings {0}", sw.ElapsedMilliseconds);


         sw.Restart();
         for (int index = 0; index < IterationCount; index++)
            Test7<TestClass>();
         sw.Stop();
         Console.WriteLine("Test7 - Generic with expression tree {0}", sw.ElapsedMilliseconds);

         // profile Baseline
         sw.Restart();
         for (int index = 0; index < IterationCount; index++)
            TestBaseline();
         sw.Stop();
         Console.WriteLine("Baseline {0}", sw.ElapsedMilliseconds);
         //Console.ReadKey(false);
      }

      public static void Test1()
      {
         var obj = Activator.CreateInstance<TestClass>();
         GC.KeepAlive(obj);
      }

      public static void Test2()
      {
         var obj = new TestClass();
         GC.KeepAlive(obj);
      }

      static Func<TestClass> Create = delegate
      {
         return new TestClass();
      };

      public static void Test3()
      {
         var obj = Create();
         GC.KeepAlive(obj);
      }

      public static void Test4<T>() where T : new()
      {
         var obj = new T();
         GC.KeepAlive(obj);
      }

      public static void Test5<T>()
      {
         var obj = ((T)Activator.CreateInstance(typeof(T)));
         GC.KeepAlive(obj);
      }

      private const BindingFlags anyAccess = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;

      public static void Test6<T>()
      {
         var obj = ((T)Activator.CreateInstance(typeof(T), anyAccess, null, null, null));
         GC.KeepAlive(obj);
      }

      public static void Test7<T>()
         where T : new()
      {
         var obj = New<T>.Instance();
         GC.KeepAlive(obj);
      }

      static TestClass x = new TestClass();
      public static void TestBaseline()
      {
         GC.KeepAlive(x);
      }
   }
```

**Comment by amaggiulli** [comment]
Interesting , but , as someone commented,  In 90% of the case it's not an issue and having a new() constraint and calling new T() is much more readable.

**Comment by igitur** [comment]
Check that sample program and look at the difference it makes if you instantiate many objects. I'll do more tests to see if there are cases where it would speed up a QLNet project much.

I don't think the `New<T>.Instance()` syntax is much less readable though.

**Comment by amaggiulli** [comment]
`public static readonly Func<T> Instance = Expression.Lambda<Func<T>>(Expression.New(typeof(T))).Compile();`

yup is easy :)

**Comment by igitur** [comment]
That's a once-off and is encapsulated in a helper class. You don't need to remember that.

**Comment by Daniel-Svensson** [comment]
First: I have only started looking into using this library so I am not proficient with naming conventions and so on, but here is some feedback.

1. God initiative +1
2. A good post on the same topic can be found on 
https://blogs.msdn.microsoft.com/seteplia/2017/02/01/dissecting-the-new-constraint-in-c-a-perfect-example-of-a-leaky-abstraction/ the FastActivator<T>.Create() seems promising and have somewhat better performance. As long as the internal API is in place it can be changed later on.
3. Naming 
    1.  Method
Having a method/func named "Instance" sound a lot like something implementing a singleton pattern and not at all like a method allocating a new object. *Create* or *New* would be much better names in my opinion. 
    2. Class
 Assuming that the method name changes something like
   * ...Factory
   * ...Activator (FastActivator as in the mentioned blog post does not sound so bad)
4. Visibility
Does it make sense to have this public to promote it as a feature for end users or should it be an implementation detail of the library and kept internal / private.

**Comment by igitur** [comment]
@Daniel-Svensson Valid points, but we've kind of put this on hold. The changes haven't really affected the run time of the unit tests, so I'm unsure whether the additional complexity is warranted. Do you have a counter-example where this change would make a real-world difference in performance?

**Comment by amaggiulli** [comment]
Thx @Daniel-Svensson , 
now that codebase is on vs 2015, reading the great post of Sergey Teplyakov this become more urgent , because now it use Activator.CreateInstance() ( aka reflection ) and this is no good .

**Pull request closed without merging**
