### PR TITLE
add support for doNET core 

### PR DESCRIPTION
**Pull request by leo90skk**
add support for [.NET Core](https://dotnet.github.io/) (#97)

Please check carefully, the unit tests failed. I can't test the origin unit tests because I do not have the unit test framework that is used before. Maybe theese tests didn't worked before.

### CODE REVIEW

**Comment by amaggiulli** [comment]
This is the log of Appveyor : 

Build started
git clone -q https://github.com/amaggiulli/qlnet.git C:\projects\qlnet
git fetch -q origin +refs/pull/100/merge:
git checkout -qf FETCH_HEAD
Patching AssemblyInfo
Patching QLNet\Properties\AssemblyInfo.cs...OK
msbuild "QLNet.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.
Cashflows\CashFlows.cs(364,55): error CS1061: 'Type' does not contain a definition for 'GetTypeInfo' and no extension method 'GetTypeInfo' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?) [C:\projects\qlnet\QLNet\QLNet.csproj]
Cashflows\CouponPricer.cs(241,52): error CS1061: 'Type' does not contain a definition for 'GetTypeInfo' and no extension method 'GetTypeInfo' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?) [C:\projects\qlnet\QLNet\QLNet.csproj]
Pricingengines\BlackCalculator.cs(323,56): error CS1061: 'Type' does not contain a definition for 'GetTypeInfo' and no extension method 'GetTypeInfo' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?) [C:\projects\qlnet\QLNet\QLNet.csproj]
Patterns\WeakEventSource.cs(112,31): error CS1061: 'Delegate' does not contain a definition for 'GetMethodInfo' and no extension method 'GetMethodInfo' accepting a first argument of type 'Delegate' could be found (are you missing a using directive or an assembly reference?) [C:\projects\qlnet\QLNet\QLNet.csproj]
Patterns\WeakEventSource.cs(132,62): error CS1061: 'Callback' does not contain a definition for 'GetMethodInfo' and no extension method 'GetMethodInfo' accepting a first argument of type 'Callback' could be found (are you missing a using directive or an assembly reference?) [C:\projects\qlnet\QLNet\QLNet.csproj]
Math\statistics\sequencestatistics.cs(107,61): error CS1061: 'Type' does not contain a definition for 'GetTypeInfo' and no extension method 'GetTypeInfo' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?) [C:\projects\qlnet\QLNet\QLNet.csproj]
Math\statistics\sequencestatistics.cs(116,61): error CS1061: 'Type' does not contain a definition for 'GetTypeInfo' and no extension method 'GetTypeInfo' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?) [C:\projects\qlnet\QLNet\QLNet.csproj]
Math\Interpolations\CubicSplineInterpolation.cs(321,34): warning CS0169: The field 'CubicSplineInterpolation.coeffs_' is never used [C:\projects\qlnet\QLNet\QLNet.csproj]
Command exited with code 1

**Comment by leo90skk** [comment]
Yea, the most errors comes from reflection....
In dotNet Core you have to use extensions like GetTypeInfo to use reflection.

Maybe we should wait to .net Core 1.1 - Microsoft plans to simplify reflections.

**Comment by amaggiulli** [comment]
I will work with you on this when I'm back to work, I'm interested at dotnet Core and all the news around that.

**Comment by amaggiulli** [comment]
branch develop in now .net core compatible

**Pull request closed without merging**
