### PR TITLE
Strong named the assembly

### PR DESCRIPTION
**Pull request by screig**
If one is to use this code, one may need to install in to the GAC. In that case it will need to be strong named.

why
[https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx]

### CODE REVIEW

**Comment by igitur** [comment]
Should we commit the snk file into the public repository? If yes, wouldn't that defeat the purpose of having it 'secretly' signed?

**Comment by screig** [comment]
I was not sure about that, secret keys and open source? Maybe amaggiulli could keep his own copy offline? 

I see the purpose of this pull request of enabling the installation in to the GAC, I don't think the key even needs to be secret?

**Comment by screig** [comment]
ps at the bottom of that link(above) Microsoft says:

"If you are an open-source developer and you want the identity benefits of a strong-named assembly, consider checking in the private key associated with an assembly into your source control system."

**Comment by amaggiulli** [comment]
QLNet , like all other open source software , is available as dll and as source code . 
This mean that users that want a strong-named version are free to sign their own clone/fork of the
source code with a minimal effort. Personally I don't like the idea of checking in the private key and sign the assembly because this will generate some extra work that instead can be used to enhance/fix the software.

**Comment by Daniel-Svensson** [comment]
I don't se how the key would result in extra work. 
As long as the project is setup to use the snk file, it will be used automatically for anyone without having to think about it at all. 👍 Please remember that snk signing is *not* about security (unfortunately the naming is a bit confusing with keyfiles and signing), it is only about *"strong naming"* so that an assembly references becomes more than just the name of the .dll 


The downside with signing would be that for desktop applications one will have to either recompile (which most people would do anyway) or apply assembly redirection when upgrading to a newer version such as from 1.7 to 1.8.  
I don't know the history of qlnet enough, but unless there is rigorous testing to confirm that binary compatibility never ever is broken between "minor" (1.7-1.8) releases this should not be a problem at all, but might be good since it indicates that some version upgrades are not a drop-in replacement. 

If it tries to be strict about semver versioning and backwards compatibility an alternative would be to only update the "informal version" between releases and keep the assembly version intact (similar to Entity Framework where 6.1.3 still uses assembly version "6.0.0").

**Pull request closed without merging**
