### PR TITLE
Add Heston Barrier & Vanilla FDM engine 

### PR DESCRIPTION
**Pull request by tournierjc**
Add engines + tests

### CODE REVIEW

**Comment by tournierjc** [comment]
Hello @amaggiulli, the test testKahlJaeckelCase is very long (4mn on my computer to run it) and seems to time out the appveyor server. Any thought?

**Comment by amaggiulli** [comment]
@tournierjc is a new test or an existing one ?

**Comment by tournierjc** [comment]
It's a new one

**Comment by amaggiulli** [comment]
@tournierjc I'll run some profiling on this test , meanwhile you can skip it in CI with this syntax : 

#if NET452
      [TestCategory("LongRun"), TestMethod()]
#else
      [Fact(Skip = "LongRun")]
#endif

**Comment by tournierjc** [comment]
Hello @amaggiulli, I don't know what's wrong. Just tried to clone my local branch and to launch the tests, everything went fine.

**Comment by amaggiulli** [comment]
@tournierjc Please skip also the following long running tests that may cause AppVeyor fails : 

- testFdmHestonConvergence
- testFdBarrierVsCached
- testFdVanillaVsCached
- testKahlJaeckelCase

**Comment by tournierjc** [comment]
Done.

**Pull request closed without merging**
