### PR TITLE
Project reference to QLNet in samples and consolidated props file

### PR DESCRIPTION
**Pull request by igitur**
This PR does 2 things

- For the samples projects, changes the QLNet package reference to a project reference. This makes it easier to debug. We can discuss this if you disagree
- Adds a new QLNet.props which contains shared project attributes. Make all projects reference this shared props file

### CODE REVIEW

**Comment by igitur** [comment]
@amaggiulli So, in the future, when you want to bump the version, you will now have only 1 file to edit: `QLNet.props`

**Comment by amaggiulli** [comment]
@igitur looks good, about samples I'm not sure what the best for users, currently they can run/debug samples withut the need to build QLNet, also when working on QLNet it do not compile samples on each changes.

**Comment by igitur** [comment]
> @igitur looks good, about samples I'm not sure what the best for users, currently they can run/debug samples withut the need to build QLNet, also when working on QLNet it do not compile samples on each changes, but now that samples are in separate solution maybe is not an issue.

How do most users use the samples at the moment? If they're using the sample code, are they not cloning the entire repo, in which case the QLNet project would be available too? I thought that this would be the general case.

I can drop that commit if you prefer.

**Comment by amaggiulli** [comment]
closing for now

**Pull request closed without merging**
